# Generated by Django 5.2.17 on 2026-10-04 04:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('type', models.CharField(choices=[('In-person', 'In-person'), ('Follow-up', 'Follow-up'), ('Emergency', 'Emergency'), ('Online', 'Online')], default='In-person', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['status'], name='appointment_status_8fe9d7_idx'), models.Index(fields=['patient', 'date'], name='appointment_patient_83aa7a_idx'), models.Index(fields=['doctor', 'date'], name='appointment_doctor__e7d63f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'Cancelled'), _negated=True), fields=('doctor', 'date', 'time'), name='unique_active_doctor_slot')],
            },
        ),
    ]
