# Generated by Django 5.2.17 on 2026-10-04 10:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('Symptom Checker', 'Symptom Checker'), ('Clinical Assistant', 'Clinical Assistant'), ('Prescription Advisory', 'Prescription Advisory'), ('No-Show Prediction', 'No-Show Prediction'), ('Health Analytics', 'Health Analytics')], db_index=True, max_length=30)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(default='local', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to='patients.patient')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('triage_result', 'Triage result'), ('clinical_summary', 'Clinical summary'), ('clinical_answer', 'Clinical answer'), ('advisory', 'Prescription advisory'), ('prediction', 'No-show prediction'), ('analytics', 'Analytics snapshot')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('confidence', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_review', models.BooleanField(default=True)),
                ('review_status', models.CharField(choices=[('Pending Review', 'Pending Review'), ('Reviewed', 'Reviewed'), ('Completed', 'Completed')], db_index=True, default='Pending Review', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_insights', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='ai.aisession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['module', 'created_at'], name='ai_aisessio_module_27a649_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['review_status'], name='ai_aiinsigh_review__d13fe6_idx'),
        ),
    ]
