# Generated by Django 5.2.17 on 2026-10-01 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_DELETED', 'User deleted'), ('PATIENT_CREATED', 'Patient created'), ('PATIENT_UPDATED', 'Patient updated'), ('PRESCRIPTION_CREATED', 'Prescription created'), ('APPOINTMENT_UPDATED', 'Appointment updated'), ('INVOICE_CREATED', 'Invoice created')], max_length=30)),
                ('module', models.CharField(max_length=50)),
                ('object_type', models.CharField(blank=True, default='', max_length=50)),
                ('object_id', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
