# Generated by Django 5.2.17 on 2026-10-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_DELETED', 'User deleted'), ('PATIENT_CREATED', 'Patient created'), ('PATIENT_UPDATED', 'Patient updated'), ('PATIENT_DELETED', 'Patient deleted'), ('DOCTOR_CREATED', 'Doctor created'), ('DOCTOR_UPDATED', 'Doctor updated'), ('DOCTOR_DELETED', 'Doctor deleted'), ('PRESCRIPTION_CREATED', 'Prescription created'), ('APPOINTMENT_CREATED', 'Appointment created'), ('APPOINTMENT_UPDATED', 'Appointment updated'), ('INVOICE_CREATED', 'Invoice created')], max_length=30),
        ),
    ]
