# Generated by Django 5.2.17 on 2026-10-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_DELETED', 'User deleted'), ('PATIENT_CREATED', 'Patient created'), ('PATIENT_UPDATED', 'Patient updated'), ('PATIENT_DELETED', 'Patient deleted'), ('DOCTOR_CREATED', 'Doctor created'), ('DOCTOR_UPDATED', 'Doctor updated'), ('DOCTOR_DELETED', 'Doctor deleted'), ('PRESCRIPTION_CREATED', 'Prescription created'), ('PRESCRIPTION_UPDATED', 'Prescription updated'), ('PRESCRIPTION_DELETED', 'Prescription deleted'), ('LAB_TEST_CREATED', 'Lab test created'), ('LAB_TEST_UPDATED', 'Lab test updated'), ('LAB_ORDER_CREATED', 'Lab order created'), ('LAB_ORDER_UPDATED', 'Lab order updated'), ('LAB_RESULT_UPDATED', 'Lab result updated'), ('MEDICINE_CREATED', 'Medicine created'), ('MEDICINE_UPDATED', 'Medicine updated'), ('BATCH_CREATED', 'Inventory batch created'), ('BATCH_UPDATED', 'Inventory batch updated'), ('DISPENSING_CREATED', 'Dispensing created'), ('DISPENSING_UPDATED', 'Dispensing updated'), ('APPOINTMENT_CREATED', 'Appointment created'), ('APPOINTMENT_UPDATED', 'Appointment updated'), ('INVOICE_CREATED', 'Invoice created'), ('INVOICE_UPDATED', 'Invoice updated'), ('INVOICE_ISSUED', 'Invoice issued'), ('INVOICE_CANCELLED', 'Invoice cancelled'), ('PAYMENT_CREATED', 'Payment recorded'), ('PAYMENT_REVERSED', 'Payment reversed')], max_length=30),
        ),
    ]
