# Generated by Django 5.2.17 on 2026-10-04 10:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('service_type', models.CharField(choices=[('Consultation', 'Consultation'), ('Laboratory', 'Laboratory'), ('Pharmacy', 'Pharmacy'), ('Procedure', 'Procedure'), ('Package', 'Package'), ('Other', 'Other')], default='Consultation', max_length=20)),
                ('issue_date', models.DateField(db_index=True)),
                ('due_date', models.DateField()),
                ('payment_terms', models.CharField(blank=True, default='', max_length=50)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='Draft', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.patient')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('Consultation', 'Consultation'), ('Laboratory', 'Laboratory'), ('Pharmacy', 'Pharmacy'), ('Procedure', 'Procedure'), ('Package', 'Package'), ('Other', 'Other')], default='Other', max_length=20)),
                ('category', models.CharField(choices=[('Consultation', 'Consultation'), ('Laboratory', 'Laboratory'), ('Medicine', 'Medicine'), ('Procedure', 'Procedure'), ('Other', 'Other')], default='Other', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'ordering': ['invoice', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile Banking', 'Mobile Banking'), ('Bank Transfer', 'Bank Transfer'), ('Insurance', 'Insurance')], max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Completed', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='patients.patient')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Consultation Revenue', 'Consultation Revenue'), ('Laboratory Revenue', 'Laboratory Revenue'), ('Pharmacy Revenue', 'Pharmacy Revenue'), ('Procedure Revenue', 'Procedure Revenue'), ('Refund', 'Refund'), ('Insurance Payment', 'Insurance Payment'), ('Adjustment', 'Adjustment')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile Banking', 'Mobile Banking'), ('Bank Transfer', 'Bank Transfer'), ('Insurance', 'Insurance')], default='', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='billing.invoice')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='patients.patient')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.payment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='billing_inv_status_541249_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient', 'issue_date'], name='billing_inv_patient_527dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='billing_pay_status_b7739e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['patient', 'payment_date'], name='billing_pay_patient_7fccf8_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuetransaction',
            index=models.Index(fields=['type'], name='billing_rev_type_577e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuetransaction',
            index=models.Index(fields=['patient', 'transaction_date'], name='billing_rev_patient_3ef710_idx'),
        ),
    ]
