# Generated by Django 5.2.17 on 2026-10-04 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensingrecord',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_records', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='dispensingitem',
            name='dispensing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.dispensingrecord'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['is_active'], name='pharmacy_me_is_acti_1c529c_idx'),
        ),
        migrations.AddField(
            model_name='dispensingitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_items', to='pharmacy.medicine'),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.medicine'),
        ),
        migrations.AddField(
            model_name='dispensingitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Source batch; auto-assigned (earliest expiry) when omitted.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_items', to='pharmacy.medicinebatch'),
        ),
        migrations.AddIndex(
            model_name='dispensingrecord',
            index=models.Index(fields=['status'], name='pharmacy_di_status_883810_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.UniqueConstraint(fields=('medicine', 'batch_number'), name='unique_medicine_batch'),
        ),
    ]
