# Generated by Django 5.2.17 on 2026-10-04 04:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('specialization', models.CharField(db_index=True, max_length=100)),
                ('qualification', models.CharField(blank=True, default='', max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9\\s\\-()]{7,20}$')])),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('department', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('room', models.CharField(blank=True, default='', max_length=50)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('On Leave', 'On Leave'), ('Off Duty', 'Off Duty')], default='Available', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Linked login account (role DOCTOR) when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_available', models.BooleanField(default=True)),
                ('slots', models.JSONField(blank=True, default=list, help_text="Time-slot labels, e.g. ['09:00 AM'].")),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor')),
            ],
            options={
                'ordering': ['doctor', 'day'],
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['status'], name='doctors_doc_status_d677b8_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['availability'], name='doctors_doc_availab_4ed977_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.UniqueConstraint(fields=('doctor', 'day'), name='unique_doctor_day'),
        ),
    ]
